[package]
name = "spire-sieve"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libgdx-xs128 = "0.1.3"
